# Generated by Django 2.1.7 on 2019-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='seo.Keyword', verbose_name='Keywords'),
        ),
    ]
