# Generated by Django 2.1.7 on 2019-04-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_auto_20190329_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
    ]
