# Generated by Django 2.1.7 on 2019-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_alt_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Logo alt text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
