# Generated by Django 2.1.7 on 2019-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='catalog.ProductCategory', verbose_name='Categories'),
        ),
    ]
