# Generated by Django 2.1.7 on 2019-03-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190329_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', related_query_name='subcategories', to='catalog.ProductCategory', verbose_name='Parent'),
        ),
    ]
