# Generated by Django 2.1.7 on 2019-03-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190331_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ProductBadge', verbose_name='Badge'),
        ),
    ]
