# Generated by Django 2.1.7 on 2019-03-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190331_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
