# Generated by Django 2.1.7 on 2019-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190331_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbadge',
            options={'verbose_name': 'badge', 'verbose_name_plural': 'badges'},
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2018-02-12 22:12', verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
