# Generated by Django 2.1.7 on 2019-04-20 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('creation_datetime', models.DateTimeField(auto_now=True, verbose_name='Creation date and time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', related_query_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accounts',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
